title: Bottles
description: Easily run Windows software on Linux with 🍷 Bottles!
author: Bottles Developers
email: mail@usebottles.com
logo: /assets/logo.svg
description: This is our the for GitHub Pages.

markdown: kramdown
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
