title: Bottles
description: Easily run Windows software on Linux with 🍷 Bottles!
author: Bottles Developers
email: mail@usebottles.com
logo: /uploads/logo.svg

markdown: kramdown
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
